#!/bin/bash
# Update and install system dependencies
sudo apt-get update
sudo apt-get install -y libproj-dev proj-data proj-bin
sudo apt-get install -y libgeos-dev
sudo apt-get install -y gdal-bin
sudo apt-get install -y libgdal-dev

# Use conda to install cartopy and its dependencies
conda install -c conda-forge cartopy matplotlib==3.6.0 netcdf4 h5netcdf
